### ISSUE TITLE
Package status and plans

### ISSUE THREAD

**Issue by itsdfish** [prbzrg/PDFEstimators.jl#9]
Hi-

Thank you for fixing the error in the normalizing flow [example](https://github.com/SciML/DiffEqFlux.jl/issues/786) at DiffEqFlux. I am interested in using normalizing flows for estimating PDFs/likelihood functions for mathematically intractable models, e.g. (https://elifesciences.org/articles/77220) . This package seems to be exactly what I am looking for, and  would be very useful to the community more broadly. What is the status of the project and what are your plans?

Thank you

**Comment by prbzrg** [comment]
I am developing a package with a different API than `DiffEqFlux`, called [ICNF.jl](https://github.com/impICNF/ICNF.jl), but it's very experimental.
This package is for wrapping other density estimation tools in a [`MLJ` API](https://alan-turing-institute.github.io/MLJ.jl/stable/). It has:
- `ActualModel` that uses `pdf` from `Distributions`
- `FittedModel` that uses `fit_mle` from `Distributions`
- `FFJORDModel` that uses `FFJORD` from `DiffEqFlux`
- `KDEModel` that uses `kde` from `KernelDensity`
- `ASHModel` that uses `ash` from `AverageShiftedHistograms`

For now, It's working, but it's not actively developing.

**Comment by itsdfish** [comment]
Sounds interesting. I will keep an eye on ICNF.jl. Thank you.
